clientside/todo-list/config/routes.rb
Rails.application.routes.draw do
  resources :todo_list_webs
  resources :microposts
  resources :users
   root 'todo_list_webs#index'
end

clientside/todo-list/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

clientside/todo-list/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140 },
                      presence: true
end

clientside/todo-list/app/models/todo_list_web.rb
class TodoListWeb < ApplicationRecord
end

clientside/todo-list/app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  validates :name, presence: true    # Replace FILL_IN with the right code.
  validates :email, presence: true    # Replace FILL_IN with the right code.
end

clientside/todo-list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  protect_from_forgery with: :exception
skip_before_action :verify_authenticity_token
end

clientside/todo-list/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

clientside/todo-list/app/controllers/todo_list_webs_controller.rb
class TodoListWebsController < ApplicationController
  before_action :set_todo_list_web, only: [:show, :edit, :update, :destroy]

  # GET /todo_list_webs
  # GET /todo_list_webs.json
  def index
    @todo_list_webs = TodoListWeb.all
  end

  # GET /todo_list_webs/1
  # GET /todo_list_webs/1.json
  def show
  end

  # GET /todo_list_webs/new
  def new
    @todo_list_web = TodoListWeb.new
  end

  # GET /todo_list_webs/1/edit
  def edit
  end

  # POST /todo_list_webs
  # POST /todo_list_webs.json
  def create
    @todo_list_web = TodoListWeb.new(todo_list_web_params)

    respond_to do |format|
      if @todo_list_web.save
        format.html { redirect_to @todo_list_web, notice: 'Todo list web was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list_web }
      else
        format.html { render :new }
        format.json { render json: @todo_list_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_list_webs/1
  # PATCH/PUT /todo_list_webs/1.json
  def update
    respond_to do |format|
      if @todo_list_web.update(todo_list_web_params)
        format.html { redirect_to @todo_list_web, notice: 'Todo list web was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list_web }
      else
        format.html { render :edit }
        format.json { render json: @todo_list_web.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_list_webs/1
  # DELETE /todo_list_webs/1.json
  def destroy
    @todo_list_web.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_webs_url, notice: 'Todo list web was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list_web
      @todo_list_web = TodoListWeb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_web_params
      params.require(:todo_list_web).permit(:title, :description, :date)
    end
end

clientside/todo-list/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

clientside/todo-list/app/helpers/application_helper.rb
module ApplicationHelper
end

clientside/todo-list/app/helpers/microposts_helper.rb
module MicropostsHelper
end

clientside/todo-list/app/helpers/todo_list_webs_helper.rb
module TodoListWebsHelper
end

clientside/todo-list/app/helpers/users_helper.rb
module UsersHelper
end

clientside/todo-list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <div style="padding:15px;width: 100%;background-color:#99CC00;clear: left;">
      <table style="width:50%">
  
  <tbody><tr>
    <td style="color:black;font-size:300%;">TodoListApp</td>
    <td><a href="https://aboa.herokuapp.com/todo_list_webs/new">New Todo</a></td>
    <td><a href="https://aboa.herokuapp.com/todo_list_webs">Show TodoList</a></td>
  </tr>
</tbody></table>
      
      
    </div>
    
   <div class="container">
	<%= yield %>
</div>
  </body>
</html>

clientside/todo-list/app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clientside/todo-list/app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

clientside/todo-list/app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

clientside/todo-list/app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

clientside/todo-list/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

clientside/todo-list/app/views/todo_list_webs/_form.html.erb
<%= form_for(@todo_list_web) do |f| %>
  <% if @todo_list_web.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list_web.errors.count, "error") %> prohibited this todo_list_web from being saved:</h2>

      <ul>
      <% @todo_list_web.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :DueDate %>
    <%= f.datetime_field :date %>
  </div>
  
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clientside/todo-list/app/views/todo_list_webs/edit.html.erb
<h1 class="todo_list_web_title">Edit Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', todo_list_webs_path %>
</div>

clientside/todo-list/app/views/todo_list_webs/index.html.erb
<% @todo_list_webs.each do |todo_list_web| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_web_title"><%= link_to todo_list_web.title, todo_list_web %></h2>
    <br></br>
    <p class="todo_list_web_sub_title"><%= todo_list_web.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_todo_list_web_path %>
</div>

clientside/todo-list/app/views/todo_list_webs/new.html.erb
<h1 class="todo_list_web_title">New Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', todo_list_webs_path %>
</div>

clientside/todo-list/app/views/todo_list_webs/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_web_title"><%= @todo_list_web.title %></h2>
<br></br>
<p class="todo_list_web_sub_title"><%= @todo_list_web.description %></p>
<p class="todo_list_web_sub_title"><%= @todo_list_web.date %></p>



<div class="links">
	<%= link_to 'Edit', edit_todo_list_web_path(@todo_list_web) %> |
	<%= link_to 'Delete', todo_list_web_path(@todo_list_web), method: :delete, data: { confirm: "Are you sure?" } %> |
  <%= link_to 'Back', todo_list_webs_path %>
</div>

clientside/todo-list/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clientside/todo-list/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

clientside/todo-list/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

clientside/todo-list/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

clientside/todo-list/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  berk:
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>